# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k4Pzdmm63b5uTaDuMIUzFqerbOao867A

**NumPy Cheatsheet**

Cheatsheet for those new to Numpy
"""

#import numpy
import numpy as np

a=[1,2,3]
 b=[4,5,6]
 #a*b throws error

"""Basics"""

#initilizing arrays
a = np.array([1,2,3])
a

b = np.array([[1,2,3],[4,5,6]])
b

#checking dimensionality
a.ndim

#checking the shape of array
a.shape

#check type and size
a.dtype

a = np.array([1,2,3], dtype="int16")

a.dtype

#total space in memory of one array element
a.itemsize

a = np.array([1,2,3], dtype="int64")
a.itemsize

#total space in memory for entire array
a.nbytes

"""Indexing"""

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

a[1, 4] #second row, fifth column

a[0, :] #first row

a[:, 2] #third column

a[0, 1:6:2] #from element 2 to 7 by twos

a[0,4] = 99
a

a[:,2] = 22 #insert 22 in third column
a

a[:,2] = [21, 23] #insert 21 and 23 in third column
a

"""Initializing arrays"""

np.zeros(10) #1d

np.zeros((3, 5)) #2d

np.zeros((3, 5, 2)) #3d

np.ones((2, 3, 4))

np.full((2, 5), 22)

np.full_like(a, 22)

#aternatively
np.full(a.shape, 22)

np.random.rand(2)

np.random.rand(2, 5)

np.random.randint(5, size=(3, 4)) #array of random ints from 0-5 (exclusive)

np.random.randint(3,5, size=(3, 4)) #array of random ints from 3-5 (exclusive; i.e., 3 or 4)

np.identity(5) #5x5 identity matrix

a = np.array([1, 2, 3])
r = np.repeat(a, 5)
r

a = np.array([[1, 2, 3]])
r = np.repeat(a, 5, axis=0)
r

"""Copy an array"""

a = np.array([1, 2, 3])
b = a.copy()
b

b[0] = 22
b

a

"""Maths"""

a = np.array([1,2,3,4])

a+2 #works with any maths operator obviously

b = np.array([4,3,2,1])

a+b

np.sin(a)

np.cos(a)

a = np.random.randint(5, size=(2, 3))
a

b = np.random.randint(3, size=(3, 2))
b

c = np.matmul(a, b) #matrix multiplication

np.linalg.det(c) #determinant of the matrix

np.linalg.inv(c) #inverse of a matrix

np.matmul(np.linalg.inv(c), c) #checks out

"""Stats"""

a = np.array([[1,2,3], [4,5,6]])
a

np.min(a)

np.max(a)

np.max(a, axis=1) #max of each row

np.max(a, axis=0) #max of each col

np.sum(a)

np.sum(a, axis=0) #col sums

"""Reshaping arrays"""

a = a.reshape((3,2))
a

np.vstack([a, a]) #vertical stack

np.hstack([a, a]) #vhorizontal stack

"""Extras"""

#np.genfromtxt("text.txt", delimiter=",")

a > 2

a[a > 2]

np.any(a > 2)

np.any(a > 2, axis=0) #apply ths function to columns

np.all(a > 2)